openapi: 3.0.3
info:
  title: Account Service API
  description: API para la gestion de cuentas bancarias
  version: 1.0.0
servers:
  - url: http://localhost:8090/api/v1
    description: Local development server
paths:
  /accounts:
    get:
      tags:
        - Account
      summary: Get all accounts
      operationId: getAllAccounts
      parameters:
        - name: customerId
          in: query
          schema:
            type: string
        - name: accountType
          in: query
          schema:
            type: string
            enum: [SAVINGS, CHECKING, FIXED_TERM]
      responses:
        '200':
          description: List of accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountResponseDTO'
    post:
      tags:
        - Account
      summary: Create a new account
      operationId: createAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRequestDTO'
      responses:
        '201':
          description: Account created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponseDTO'
        '400':
          description: Invalid request

  /accounts/{id}:
    get:
      tags:
        - Account
      summary: Get account by ID
      operationId: getAccountById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Account found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponseDTO'
    put:
      tags:
        - Account
      summary: Update account
      operationId: updateAccount
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRequestDTO'
      responses:
        '200':
          description: Account updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponseDTO'
        '400':
          description: Invalid request
    delete:
      tags:
        - Account
      summary: Delete account
      operationId: deleteAccount
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Account deleted successfully
        '404':
          description: Account not found

  /accounts/{id}/balance:
    get:
      tags:
        - Account
      summary: Get account balance
      operationId: getAccountBalance
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Account balance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponseDTO'

  /accounts/fee-check:
    post:
      tags:
        - Account
      summary: Transaction fee verification
      operationId: checkTransactionFee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionFeeRequestDTO'
      responses:
        '200':
          description: Transaction fee check result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionFeeResponseDTO'

  /accounts/deposit:
    post:
      tags:
        - Account
      summary: Deposit to a bank account
      operationId: depositToAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepositRequestDTO'
      responses:
        '200':
          description: Results of the deposit to account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseDTO'

  /accounts/withdraw:
    post:
      tags:
        - Account
      summary: Bank account withdrawal
      operationId: withdrawalToAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WithdrawalRequestDTO'
      responses:
        '200':
          description: Account withdrawal results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseDTO'

  /accounts/transfer:
    post:
      tags:
        - Account
      summary: Bank transfer
      operationId: bankTransfer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequestDTO'
      responses:
        '200':
          description: Results of the transfer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseDTO'

components:
  schemas:
    AccountRequestDTO:
      type: object
      required:
        - customerId
        - accountType
        - currency
      properties:
        customerId:
          type: string
          description: Identificador de cliente
        accountType:
          type: string
          enum: [SAVINGS, CHECKING, FIXED_TERM, SAVINGS_VIP, CHECKING_PYME]
          description: Tipo de cuenta bancaria
        currency:
          type: string
          description: Tipo de moneda
        initialBalance:
          type: number
          description: Saldo inicial
        maintenanceFee:
          type: number
          description: Comision por mantenimiento
        monthlyMovementLimit:
          type: integer
          description: Numero maximo de transacciones mensuales
        withdrawalDate:
          type: integer
          minimum: 1
          maximum: 31
          description: Dia del mes permitido para transacciones
        accountHolders:
          type: array
          description: Lista de titulares de la cuenta (obligatorio al menos uno)
          items:
            $ref: '#/components/schemas/AccountHolderDTO'
        authorizedSigners:
          type: array
          description: Lista de firmantes autorizados (opcional)
          items:
            $ref: '#/components/schemas/AuthorizedSignerDTO'

    AccountResponseDTO:
      type: object
      properties:
        id:
          type: string
          description: Identificador de cuenta bancaria
        customerId:
          type: string
          description: Identificador de cliente
        accountType:
          type: string
          enum: [SAVINGS, CHECKING, FIXED_TERM, SAVINGS_VIP, CHECKING_PYME]
          description: Tipo de cuenta bancaria
        accountNumber:
          type: string
          description: Numero de cuenta bancaria
        currency:
          type: string
          description: Tipo de moneda
        balance:
          type: number
          description: Saldo de la cuenta bancaria
        maintenanceFee:
          type: number
          description: Comision por mantenimiento
        monthlyMovementLimit:
          type: integer
          description: Numero maximo de transacciones mensuales
        currentMonthMovements:
          type: integer
          description: Numero de transacciones realizadas
        withdrawalDate:
          type: string
          format: date
          description: Dia del mes permitido para transacciones
        status:
          type: string
          enum: [ACTIVE, INACTIVE, BLOCKED]
          description: Estado de la cuanta bancaria
        accountHolders:
          type: array
          description: Lista de titulares de la cuenta (obligatorio al menos uno)
          items:
            $ref: '#/components/schemas/AccountHolderDTO'
        authorizedSigners:
          type: array
          description: Lista de firmantes autorizados (opcional)
          items:
            $ref: '#/components/schemas/AuthorizedSignerDTO'
        createdAt:
          type: string
          format: date-time
          description: Fecha de creación de la cuanta bancaria
        updatedAt:
          type: string
          format: date-time
          description: Fecha de actualización de la cuanta bancaria

    AccountHolderDTO:
      type: object
      required:
        - documentNumber
        - holderType
        - signatureType
      properties:
        documentNumber:
          type: string
          description: Número de documento del titular
        name:
          type: string
          description: Nombre completo del titular
        holderType:
          type: string
          enum: [PRIMARY, SECONDARY]
          description: Tipo de titular (PRIMARY para titular principal, SECONDARY para cotitulares)
        signatureType:
          type: string
          enum: [INDIVIDUAL, JOINT]
          description: Tipo de firma requerida para operaciones

    AuthorizedSignerDTO:
      type: object
      required:
        - documentNumber
        - signatureType
        - transactionLimit
      properties:
        documentNumber:
          type: string
          description: Número de documento del firmante
        name:
          type: string
          description: Nombre completo del firmante
        position:
          type: string
          description: Cargo en la empresa (opcional)
        signatureType:
          type: string
          enum: [INDIVIDUAL, JOINT]
          description: Tipo de firma requerida para operaciones
        transactionLimit:
          type: number
          description: Límite máximo por transacción (opcional)

    BalanceResponseDTO:
      type: object
      properties:
        accountId:
          type: string
          description: Identificador de cuenta bancaria
        balance:
          type: number
          description: Saldo de la cuenta bancaria
        availableBalance:
          type: number
          description: Saldo disponible de la cuenta bancaria
        currency:
          type: string
          description: Tipo de moneda
        lastUpdateDate:
          type: string
          format: date-time
          description: Fecha de ultima actualización de la cuanta bancaria

    ApiResponseDTO:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        error:
          type: string

    TransactionFeeRequestDTO:
      type: object
      required:
        - transactionType
        - accountId
      properties:
        transactionType:
          type: string
          enum: [DEPOSIT, WITHDRAWAL, PAYMENT, CREDIT_CHARGE, TRANSFER]
          description: Tipo de transaccion
        accountId:
          type: string
          description: Identificador de cuenta bancaria

    TransactionFeeResponseDTO:
      type: object
      properties:
        subjectToFee:
          type: boolean
          description: Estado para verificar si aplica comision
        feeAmount:
          type: number
          description: Monto de comision

    DepositRequestDTO:
      type: object
      required:
        - targetAccountId
        - amount
      properties:
        targetAccountId:
          type: string
          description: Identificador de cuenta destino de deposito
        amount:
          type: number
          description: Monto de deposito
        feeAmount:
          type: number
          description: Monto de comision
        description:
          type: string
          description: Descripcion de deposito

    WithdrawalRequestDTO:
      type: object
      required:
        - sourceAccountId
        - amount
      properties:
        sourceAccountId:
          type: string
          description: Identificador de cuenta origen de retiro
        amount:
          type: number
          description: Monto de retiro
        feeAmount:
          type: number
          description: Monto de comision
        description:
          type: string
          description: Descripcion de retiro

    TransferRequestDTO:
      type: object
      required:
        - sourceAccountId
        - targetAccountId
        - amount
      properties:
        sourceAccountId:
          type: string
          description: Identificador de cuenta origen
        targetAccountId:
          type: string
          description: Identificador de cuenta destino
        amount:
          type: number
          description: Monto de transferencia
        description:
          type: string
          description: Descripcion de transferencia
